name: Check if app can be run
on: 
  push:
    branches: [master]
  # pull_request:
  #   branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up node environment
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Installing node modules
        run: npm ci

      - name: Running tests
        run: npm run test

      - name: Running eslint
        run: npm run lint

  deploy:
    runs-on: ubuntu-latest
    needs: test
    timeout-minutes: 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # - name: Build project
      #   run: npm ci

      - name: Copy files to remote
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOSTNAME }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: "./"
          target: ${{ secrets.TARGET_DIR }}